# Generated by Django 5.1.1 on 2024-10-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_appointment_patient_appointment_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='book_appointments',
        ),
    ]
