# Generated by Django 5.1.2 on 2024-10-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_bookappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='reason',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='issue',
            field=models.CharField(blank=True, db_column='issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='patientid',
            field=models.IntegerField(blank=True, db_column='patientid', null=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='date',
            field=models.CharField(db_column='date', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='time',
            field=models.CharField(db_column='time', max_length=255),
        ),
    ]
