# Generated by Django 5.1.1 on 2024-10-13 10:13

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_bookappointment_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='id',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='appointment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
