# Generated by Django 5.0.7 on 2024-10-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_patientid_bookappointment_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='patientid',
            field=models.IntegerField(blank=True, db_column='patientid', null=True),
        ),
    ]
