# Generated by Django 5.0.7 on 2024-10-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_patientid_bookappointment_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='patient_id',
            new_name='patientid',
        ),
    ]
