# Generated by Django 5.0.7 on 2024-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_patient_id_bookappointment_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
