# Generated by Django 5.0.7 on 2024-10-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_bookappointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
