# Generated by Django 5.0.7 on 2024-10-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_remove_appointment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False},
        ),
    ]
