# Generated by Django 5.0.7 on 2024-10-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_newpatient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newpatient',
            table='newpatient',
        ),
    ]
