# Generated by Django 5.0.7 on 2024-10-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_newpatient_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpatient',
            old_name='contact_number',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='newpatient',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='newpatient',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='newpatient',
            old_name='username',
            new_name='patientid',
        ),
    ]
